### PR TITLE
Improved LeetCode Discord Bot with User Comparison and Express.js Conversion

### PR DESCRIPTION
**Pull request by ag21o9**
fixes issue #1 
fixes issue #3 

This PR addresses issue #1  and issue #3  by introducing a new user comparison feature and migrating the LeetCode Discord bot code to Express.js.

### New Feature: User Comparison

A new command, ;compare, allows users to compare two LeetCode profiles by entering usernames as arguments (e.g., ;compare username1 username2).
The bot retrieves and displays contest data for both users, including:
Contests Attended
Rating
Top Percentage
Badge (if applicable)
This feature fosters healthy competition and analysis among users.

### Express.js Conversion

The codebase has been successfully migrated from its original form to Express.js, providing a more efficient and structured framework.
This conversion offers several benefits:
Improved code organization and maintainability through separation of concerns.
Enhanced scalability for potential future features.
Adherence to a widely used and popular Node.js framework.
Existing Commands

The bot continues to support the following commands:

**;potd:** Shows the daily LeetCode challenge.
**;random:** Displays a random LeetCode problem.
**;user** <username>: Retrieves and displays user information (contest data, streak, etc.).
**;streak** <username>: Shows the current LeetCode streak for a user.
**;help**: Provides a list of available commands and their functionalities.

Screenshot 2024-10-02 113455

### CODE REVIEW

**Comment by ag21o9** [comment]
Please checkout and let me know about the other changes

**Comment by adarsh-site** [comment]
I've my exam tomorrow. I'll start reviewing PR from 4th October.

**Comment by ag21o9** [comment]
sure , all the best for it

**Comment by ag21o9** [comment]
Can you review it now

**Comment by adarsh-site** [comment]
@ag21o9 pr has some merge conflicts. please fix it.

**Comment by BhairabMahanta** [comment]
Hey, the new merge now allows a systematic command handling!
you might be needing to change a little bit of your code. It's nothing much, just rather go to the commands folder and inside it, choose leetcode folder, create a new .mjs file and import what dependencies you require and follow this format to 

export default {
  name: "potd",
  description: "Shows the LeetCode Daily Challenge",
  aliases: ["lcd", "daily"], // Add aliases here
  async execute(client, message, args) {
  }
  
  make commands work.

**Comment by ag21o9** [comment]
I will resolve the merge conflicts

**Comment by ag21o9** [comment]
I have solved the merge conflicts
you can have a check and merge

**Comment by ag21o9** [comment]
Can you review it now

**Comment by adarsh-site** [comment]
@ag21o9 pr still has some merge conflicts. please fix it.

**Comment by ag21o9** [comment]
Check Out now please

**Comment by ag21o9** [comment]
please refer and merge now

**Comment by adarsh-site** [comment]
I don't believe this feature serves any practical purpose, so we will not proceed with it.

**Pull request closed without merging**
