### PR TITLE
Refactored Most of the bot with easier scalability!

### PR DESCRIPTION
**Pull request by BhairabMahanta**
#2 Completed 90% of the issue raised!

- Added a easy to run vscode module to simply run the code in vscode without stepping into the terminal 
image
- Added automated Help comand support 
image
- Added Aliases to commands
- Folder Directories under commands folder can be structured any way the author wants, and the code would run as long as the files end with .mjs
 #image

- So Whats left? Things like database integration which is up to the author's discretion. I may add a registration to bot, cooldowns to commands and much more!

### CODE REVIEW

**Comment by BhairabMahanta** [comment]
Please let me know any changes/additions or issues regarding the pull request!

**Comment by adarsh-site** [comment]
I am currently busy. I will start reviewing after October 4th.

**Comment by BhairabMahanta** [comment]
> I am currently busy. I will start reviewing after October 4th.

All good. Thank you for managing this repo!

**Comment by BhairabMahanta** [comment]
I think the conflict is not making much sense :0

**Pull request closed without merging**
